name: Build and Test Linux
on:
  workflow_call:
    inputs:

jobs:
  build-and-test-linux:
    needs: build-params
    uses: ./.github/workflows/build_linux.yml
    strategy:
      fail-fast: false
      matrix:
        include:
          - os-version: "22.04"
            c-compiler: "gcc-9"
            cxx-compiler: "g++-9"

          - os-version: "22.04"
            c-compiler: "gcc-11"
            cxx-compiler: "g++-11"

          - os-version: "22.04"
            c-compiler: "gcc-12"
            cxx-compiler: "g++-12"
            run-tests: true

          - job-name: "use system libraries"
            os-version: "24.04"
            c-compiler: "gcc-13"
            cxx-compiler: "g++-13"
            use-syslibs: true

          - job-name: "shared libscsynth"
            os-version: "24.04"
            c-compiler: "gcc-14"
            cxx-compiler: "g++-14"
            shared-libscsynth: true
            
          - os-version: "22.04"
            c-compiler: "clang-11"
            cxx-compiler: "clang++-11"

          - os-version: "24.04"
            c-compiler: "clang-15"
            cxx-compiler: "clang++-15"

          - os-version: "24.04"
            c-compiler: "clang-16"
            cxx-compiler: "clang++-16"

          - os-version: "24.04"
            c-compiler: "clang-17"
            cxx-compiler: "clang++-17"

          - os-version: "24.04"
            c-compiler: "clang-18"
            cxx-compiler: "clang++-18"

    with:
      sc-version: ${{ needs.build-params.outputs.sc-version }}
      job-name: ${{ matrix.job-name || '' }}
      os-version: ${{ matrix.os-version }}
      c-compiler: ${{ matrix.c-compiler }}
      cxx-compiler: ${{ matrix.cxx-compiler }}
      use-syslibs: ${{ matrix.use-syslibs || false }}
      shared-libscsynth: ${{ matrix.shared-libscsynth || false }}
      run-tests: ${{ matrix.run-tests || false }}
    secrets: inherit
