name: Test Mac OS
on:
  workflow_call:
    inputs:
      artifact-file:
        required: true
        type: string

jobs:
  test-macos:
    runs-on: macos-12
    strategy:
      fail-fast: false
      matrix:
        test-clump: [0,1,2,3,4]
    env:
      INSTALL_PATH: ${{ github.workspace }}/build/Install
      ARTIFACT_FILE: ${{ inputs.artifact-file }}
      SCLANG: build/Install/SuperCollider/SuperCollider.app/Contents/MacOS/sclang

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: false # don't need submodules for testing

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.ARTIFACT_FILE }}
          path: ${{ env.INSTALL_PATH }}

      - name: Extract artifact
        run: |
          cd "$INSTALL_PATH"
          echo Contents of `pwd`:
          ls
          hdiutil attach $ARTIFACT_FILE
          echo "mkdir SuperCollider"
          mkdir SuperCollider
          cp -R /Volumes/SuperCollider/* SuperCollider/

      - name: Setup environment
        env:
          HOMEBREW_NO_ANALYTICS: 1
          HOMEBREW_NO_AUTO_UPDATE: 1
          HOMEBREW_NO_INSTALL_CLEANUP: 1
        run: brew install coreutils # to get 'timeout' utility

      - name: Run tests
        shell: bash
        run: ./testsuite/scripts/test_ci.sh ${{ env.SCLANG }} ${{ strategy.job-index }} ${{ strategy.job-total }}
