name: Test Linux
on:
  workflow_call:
    inputs:
      artifact-file:
        required: true
        type: string
      os:
        required: true
        type: string

env:
  INSTALL_PATH: build/Install
  ARTIFACT_FILE: ${{ inputs.artifact-file }}
  SCLANG: build/Install/bin/sclang
  TESTS_PATH: testsuite/classlibrary
  SCRIPT_ADD_PATH: testsuite/scripts/add_include_path.scd
  SCRIPT_PRINT_RESULTS: testsuite/scripts/print_results.scd
  SCRIPT_RUN_TESTS: testsuite/scripts/sclang_test_runner.scd

jobs:
  test-linux:
    runs-on: ${{ inputs.os }}
    timeout-minutes: 15
    outputs:
      job-total: ${{ strategy.job-total }}
    strategy:
      fail-fast: false
      matrix:
        # the length of this array determines how many jobs are used to partition the jobs.
        # the array contents are not used (suggest just counting up from 0).
        # array must be non-empty, otherwise tests won't run!
        id: [0,1,2,3,4]
    name: "Test Linux (${{ strategy.job-index }}th test clump)"
    env:
      TEST_LIST_PROTO: testsuite/scripts/test_run_proto_gha.scd
      TEST_LIST_RESULT: testsuite/scripts/run/gha_result_${{ strategy.job-index }}.scxtar
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: false # don't need submodules for testing

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.ARTIFACT_FILE }}
          path: ${{ env.INSTALL_PATH }}

      - name: Extract artifact
        run: |
          cd "$INSTALL_PATH"
          echo Contents of `pwd`:
          ls
          unzip $ARTIFACT_FILE.zip

      - name: Setup environment
        run: |
          # install dependencies
          sudo apt-get update
          sudo apt-get install --yes libsndfile1 libavahi-client-dev libfftw3-dev libicu-dev libudev-dev qt6-base-dev libqt6svg6-dev qt6-webengine-dev libqt6webenginecore6-bin jackd1 socat

          # add bin to PATH so that scsynth can be found
          echo "$INSTALL_PATH/bin" >> $GITHUB_PATH

          # start jack
          jackd --no-realtime --silent -d dummy &

          # start virtual display server
          export DISPLAY=:99
          echo "DISPLAY=$DISPLAY" >> $GITHUB_ENV
          Xvfb $DISPLAY -screen 0 1024x768x16 &

      - name: Run tests
        shell: bash
        continue-on-error: true
        run: |
          # add path
          $SCLANG $SCRIPT_ADD_PATH $TESTS_PATH
          # run tests
          timeout 1200 $SCLANG $SCRIPT_RUN_TESTS $TEST_LIST_PROTO $TEST_LIST_RESULT ${{ strategy.job-index }} ${{ strategy.job-total }}

      - name: Post test results
        shell: bash
        run: |
          timeout 1m $SCLANG $SCRIPT_PRINT_RESULTS $TEST_LIST_RESULT

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-list-result-${{ inputs.os }}-${{ strategy.job-index }}
          path: ${{ env.TEST_LIST_RESULT }}

  results:
    runs-on: ${{ inputs.os }}
    if: always() && needs.test-linux.outputs.job-total > 1
    needs: test-linux
    timeout-minutes: 15
    name: Print combined results
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: false # don't need submodules for testing

      - name: Download test results
        uses: actions/download-artifact@v4
        with:
          pattern: 'testsuite/scripts/run/gha_result_*.scxtar'
          merge-multiple: true

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.ARTIFACT_FILE }}
          path: ${{ env.INSTALL_PATH }}

      - name: Extract artifact
        run: |
          cd "$INSTALL_PATH"
          echo Contents of `pwd`:
          ls
          unzip $ARTIFACT_FILE.zip

      - name: Setup environment
        run: |
          # install dependencies
          sudo apt-get update
          sudo apt-get install --yes libsndfile1 libavahi-client-dev libfftw3-dev libicu-dev libudev-dev qt6-base-dev libqt6svg6-dev qt6-webengine-dev libqt6webenginecore6-bin jackd1 socat

          # add bin to PATH so that scsynth can be found
          echo "$INSTALL_PATH/bin" >> $GITHUB_PATH

          # start jack
          jackd --no-realtime --silent -d dummy &

          # start virtual display server
          export DISPLAY=:99
          echo "DISPLAY=$DISPLAY" >> $GITHUB_ENV
          Xvfb $DISPLAY -screen 0 1024x768x16 &


      - name: Post combined results
        shell: bash
        run: |
          timeout 1m $SCLANG $SCRIPT_PRINT_RESULTS $(echo testsuite/scripts/run/gha_result_*.scxtar)
